### ISSUE TITLE
Update-DatabricksSQLEndpoint error

### ISSUE THREAD

**Issue by saldroubi** [gbrueckl/Databricks.API.PowerShell#57]
Getting an error when trying to update a SQLendPoint using Update-DatabricksSQLEndpoint as shown below:

Invoke-RestMethod: /Users/saldroubi/.local/share/powershell/Modules/DatabricksPS/1.9.9.11/Public/General.ps1:96:13
Line |
  96 |  …   $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error_code":"ENDPOINT_NOT_FOUND","message":"No API found for 'POST /sql/endpoints/1a273c069ef6dadc'"}

I believe the problem is that the API is not conforming to the expected edit API call.  Looking at the code in file SQLEndpointAPI.ps1 line 359 it is set  to $apiEndpoint = "/2.0/sql/config/endpoints"
but the API specification is different:  https://learn.microsoft.com/en-us/azure/databricks/sql/api/sql-endpoints#--edit

Could you please this?
Thank you very much for this very helpful module.

**Comment by gbrueckl** [comment]
Seems like the API was also renamed recently
Will have a look and fix this in the next weeks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: saldroubi ***@***.***>
Sent: Saturday, September 24, 2022 1:47:10 AM
To: gbrueckl/Databricks.API.PowerShell ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gbrueckl/Databricks.API.PowerShell] Update-DatabricksSQLEndpoint error (Issue #57)


Getting an error when trying to update a SQLendPoint using Update-DatabricksSQLEndpoint as shown below:

Invoke-RestMethod: /Users/saldroubi/.local/share/powershell/Modules/DatabricksPS/1.9.9.11/Public/General.ps1:96:13
Line |
96 | … $result = Invoke-RestMethod -Uri $apiUrl -Method $Method -Headers $ …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| {"error_code":"ENDPOINT_NOT_FOUND","message":"No API found for 'POST /sql/endpoints/1a273c069ef6dadc'"}

I believe the problem is that the API is not conforming to the expected edit API call. Looking at the code in file SQLEndpointAPI.ps1 line 359 it is set to $apiEndpoint = "/2.0/sql/config/endpoints"
but the API specification is different: https://learn.microsoft.com/en-us/azure/databricks/sql/api/sql-endpoints#--edit

Could you please this?
Thank you very much for this very helpful module.

**Comment by gbrueckl** [comment]
I just updated the module to v1.9.9.12 and the Update should now work
https://www.powershellgallery.com/packages/DatabricksPS/1.9.9.12

I also renamed the cmdlets to use the term "Warehouse" instead of "Endpoint"
so it will be `Update-DatabricksSQLWarehouse` (the old code should still work though)

**Comment by saldroubi** [comment]
I was trying to test this, however, when I tried to download the module from GitHub it is still version 1.9.9.11.  Could you update the Github with the latest version?

**Comment by saldroubi** [comment]
Ok, I got the module from PowerShell Galley.  I am getting another error when I call  Update-DatabricksSQLWarehouse on line 203.  Here is the error:

Line |
 203 |  … ty -Name "tags" -Value @{custom_tags = ConvertTo-KeyValueArray $tags}
     |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

I think it is because I am not passing any tags and line 203 just adds that parameter even though it is should be optional. 
In Update-DatabricksSQLWarehouse you check which parameters are passed but not in Update-DatabricksSQLWarehouse 

Could you please fix and I will test again. 
Also, if you could update Githup with latest.

**Comment by gbrueckl** [comment]
sure, it is optional, but if you provide `""` which is actually a value, it has to match the `AllowedSet("CHANNEL_NAME_PREVIEW,CHANNEL_NAME_CURRENT")` defined for the parameter which obviously is not the case
but especially for `-Channel` and `-Tags` the code works slightly different as the values are modified before being passed to the API hence I removed them now from being sourced by piped properties 
So if you want to change `Channel` or `Tags` now you need to explicitly add them to your `Update-DatabricksSQLWarehouse` statement as real parameters

this was done in 1.9.9.14 which is published to gallery and I also updated the code in the repo

**Comment by saldroubi** [comment]
I tested this and is working now.   Thank you for fixing it.
